# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160614_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='osmid',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
