# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160615_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='ponto',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
